### PR TITLE
ic.kppm

### PR DESCRIPTION
**Pull request by rasmuswaagepetersen**
Hi Adrian and Ege,

Here is a new procedure implementing information criteria for selection intensity function models. Note I include the point pattern data X as an argument for the procedure since I did not know how to extract it from a ppm object.

Best,

Rasmus.

### CODE REVIEW

**Comment by rubak** [comment]
Hi Rasmus,
You shouldn't include the dll file. Could you try to revert the latest commit and push to GitHub again. Then this pull request should automatically be updated. You can revert in different ways, but in this case maybe the easiest is simply to delete the dll file and then commit the deletion. Alternatively I think you can also do a point and click revert of a commit directly on GitHub, but I can't remember the details.
Cheers,
Ege

**Comment by baddstats** [comment]
Thank you very much, Rasmus.

To extract the original data pattern from a `ppm` object, use `data.ppm`. 

I will accept the pull request, and then slightly modify the code to make use of this.

best wishes 
Adrian

**Comment by baddstats** [comment]
Dear Ege and Rasmus, 
could you please check that my modification of the code is still doing what you intended?
thanks
A

**Comment by rasmuswaagepetersen** [comment]
OK, I could not find the file via Rstudio, but I deleted it on Github and committed the change followed by a pull request.

Best,

Rasmus.

*******************************************************
Rasmus Waagepetersen, Professor, Ph.D.

Department of Mathematical Sciences
Aalborg University
Skjernvej 4A
DK-9220 Aalborg

phone: +45 3122 4299 (mobile)
email: ***@***.******@***.***>
webpage: people.math.aau.dk/~rw

*******************************************************

**Comment by rasmuswaagepetersen** [comment]
Dear Adrian and Ege,

It looks fine. Thank you both for helping with adding this code to spatstat. It answers a question I got from a Chinese biologist back in 2008. Better late than never :)

Best,

Rasmus.



*******************************************************
Rasmus Waagepetersen, Professor, Ph.D.

Department of Mathematical Sciences
Aalborg University
Skjernvej 4A
DK-9220 Aalborg

phone: +45 3122 4299 (mobile)
email: ***@***.******@***.***>
webpage: people.math.aau.dk/~rw

*******************************************************

**Pull request merged**
