### PR TITLE
Implementation of Adaptive Second Order Composite Likelihood

### PR DESCRIPTION
**Pull request by cfend**
Implementation of the paper "Adaptive estimating function inference for nonstationary determinantal point processes" (Lavancier et al, 2021) for cluster/cox models and DPPs.

### CODE REVIEW

**Comment by rubak** [comment]
There was a small conflict regarding the package version in DESCRIPTION which I quickly fixed to make it possible to merge this. Also we would need to put the new package `nleqslv` in `Suggests:` of DESCRIPTION, and then make this code conditional on that package being present. This is something we need to consider and it may take some time before we decide since we really try to have as few dependencies as possible for spatstat packages. The good thing about `nleqslv` is that it is a well established package which has been on CRAN since 2009 and has quite a few other reverse dependencies, so it seems stable and trustworthy.

**Review by rubak — COMMENTED** [review]
Could you try the following things to see if it helps to pass the automated checks:

- [ ] Add `nleqslv` to `Suggests:` in DESCRIPTION.
- [ ] Add `if(!requireNamespace(nleqslv)){.....} in the very beginning of `kppmCLadap` to tell the user that this package is needed.
- [ ] Change the call `nleqslv()` to `nleqslv::nleqslv()`.
- [ ] Add `importFrom(nleqslv, nleqslv)` to NAMESPACE.
- [ ] Add a few tests of the function to testsK.R. You can see https://github.com/spatstat/spatstat.core/blob/c14f35c7b96ff7edf7a9385025795f7f01c3a2e6/tests/testsK.R#L390-L399 for inspiration, and you should wrap the test code in `if(requireNamespace(nleqslv)){.....}` so it is only run if the package is installed.

**Comment by baddstats** [comment]
Dear Chiara Fend, thank you for offering this code. 

It would have been useful to include a covering note summarising the changes. 

There are some changes that will require careful consideration. 

Your code would require us to add the package `nleqslv` to the list of Required or Suggested packages. CRAN is pressing us to reduce the number of dependencies. Do you have a good reason for using this package instead of the inbuilt `optim` function?

The code also makes changes to the internal book-keeping of spatstat (eg the cluster process information table in `clusterinfo.R`).  Could you please reassure me that these changes would not change the behaviour of existing functions in `spatstat`.

Some of the code appears to have been written by editing older versions of the `spatstat` source code. We will need to check that it is compatible with the current version of `spatstat.core` on GitHub.

We will look through this code carefully when we have time.

regards, Adrian Baddeley

**Comment by cfend** [comment]
Dear Adrian Baddeley,

the proposed adaptive estimating function is (compared to the other methods) the only non-scalar valued function. In particular we need to solve an equation f(theta) = 0 where f: R^d to R^d where d is the number of parameters to be estimated. 

I do not have that much experience with nonlinear equation solvers in R so I went with the optimizer that Lavancier et al used in their basic implementation. I did not try to reformulate the proposed approach as a scalar valued minimization problem which could then be solved by `optim`.

Concerning the model tables, I talked in the beginning with Ege about where to include the gradients of the pair correlation functions as they are needed when setting up the estimating function (and I wanted to refrain from having to use the `Deriv` package or others). In my tests I did not experience any effects of the added properties in particular on the other fitting methods.

Thank you for taking the code into consideration.

Best, Chiara Fend

**Comment by baddstats** [comment]
This code is now included in the public release `spatstat.core 2.3-0` with some changes.

**Pull request merged**
