### PR TITLE
intensity.interact and dpp approximation in intensity.ppm

### PR DESCRIPTION
**Pull request by lavancier-f**

### CODE REVIEW

**Comment by baddstats** [comment]
Thank you for this contribution!

I will make some modifications to this code before integrating it into `spatstat.core`.

**Comment by baddstats** [comment]
I can't agree to all of these changes because it would change the meaning of some of the `spatstat` classes.

An object of class `interact` represents the interaction structure, without coefficients, which are yet to be estimated. It doesn't make sense to have a method for `intensity` for this class. The arguments in your function `intensity.interact` would define a Gibbs point process. So it seems to me that what we need is a new class that represents a Gibbs process defined by parameters rather than fitted to data. (This has been under discussion for a while).

An object of class `fii` (fitted interaction) represents the fitted interaction. It contains an `interact` object and a set of fitted interaction coefficients. It is not appropriate to add a new argument `co` to `PoissSaddlePairwise(beta, fi)` because the `fi` already contains the required coefficients.

I will make appropriate adjustments and incorporate this code in `spatstat.core`

Thanks again

**Comment by baddstats** [comment]
Another problem is that the code would refuse to calculate intensity for higher-order interactions `Geyer` and `AreaInter` which are currently supported

**Comment by lavancier-f** [comment]
Dear Adrian, 
Thank you to take my changes into consideration. 
I agree that a new class for Gibbs models would be more suited than using interact + some coefficients. Also I only considered pairwise interactions, but you are right that higher interactions could be included as well (for the Poisson saddlepoint method). 
You can of course modify anything you want in the code. I am happy to help if needed at any point.
Thank you again.

**Comment by baddstats** [comment]
I will incorporate this code now.

**Pull request closed without merging**
